### PR TITLE
Updated icon as suggestion

### PR DESCRIPTION
**Pull request by mrmckeb**
Minor update to icon to make it less dominating in UI, and hopefully a little more descriptive. Also hoping to differentiate from other icons using play-like button.

### CODE REVIEW

**Comment by mrmckeb** [comment]
If you like this, I can also take a look at adding colours into the icon to represent states of activity when version 2 comes along. Otherwise, and again, great plugin.

**Comment by daPhyre** [comment]
Ah! You meant this icon. Yes, I think this could work better as you say, I'll test it on my own.

Probably a "compiling" state might work as well, I don't know which other state you have in mind too. Please let me know about your ideas. Thank you for this!

**Comment by mrmckeb** [comment]
No problem. I definitely think a compiling (and maybe error) state could be useful. I can update the SVG/CSS to have all of that, then you can just add JavaScript to change the state as you'd like? Let me know what you think, I should have some time to do that over the next day or two.

You could also set a disabled (0.4 opacity) state for when the current document isn't a JS file, but for people with a settings file (compiling multiple JS files), that's probably not so helpful.

**Comment by mrmckeb** [comment]
Hey there, did you want me to update the icon with additional states? Or did you want to wait for version 2?

**Comment by daPhyre** [comment]
Update it please, the running state will be indeed implemented. As for the error state, I have been long time thinking on how to dismiss it, and I think it might not be the best for now, as probably it will get stuck in that state for long time, which would make it an undesirable state, so I'll leave that only to the Progress Panel.

Thanks!

**Pull request merged**
